### PR TITLE
Add support for covers from URLs. Add support for PNG covers.

### LINKED ISSUE #54: Add support for deck covers of any file type, from URL
## What? Why?

#49 added support for JPEG deck covers loaded from local files.
However, it would be nice to

- be able to set covers from existing image URLs (as suggested [here](https://github.com/floscha/tinycards-python-api/pull/49#issuecomment-473534845) by @floscha),
- handle other formats (e.g. PNG).

In order to do this, the `coverImageUrl` field would have to be supported.

## How?

Below is an extract of requests/responses with the fields relevant to covers, when manually interacting with decks on https://tinycards.duolingo.com.

### Observations
- **Invariant 1.**: before a custom cover is set, `coverImageUrl` is always `null`.
- **Invariant 2.**: in deck updates, even for deck cover updates, `coverImageUrl` is always sent back, with the latest value received from the server-side, i.e. `null` if no custom cover, or the last known URL to server-side otherwise.
- **Invariant 3.**: responses from `POST`s/`PATCH`s requests and subsequent `GET` requests are always equivalent w.r.t. to `imageUrl` and `coverImageUrl`.

### 1. Deck creation w/o cover:
`POST` https://tinycards.duolingo.com/api/1/decks
- no `imageFile` field
- no `imageUrl` field
- no `imageCoverUrl` field
Response:
```json
{
  "coverImageUrl": null,
  "imageUrl": "https://s3.amazonaws.com/tinycards/image/16cb6cbcb086ae0f622d1cfb7553a096"
}
```

### 2. Subsequent deck loading:
`GET` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": null,
  "imageUrl": "https://s3.amazonaws.com/tinycards/image/16cb6cbcb086ae0f622d1cfb7553a096",
}
```

### 3. Deck cards update:
`PATCH` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": null
}
```
Response:
```json
{
"coverImageUrl": null,
"imageUrl": "https://s3.amazonaws.com/tinycards/image/16cb6cbcb086ae0f622d1cfb7553a096"
}
```

### 4. Subsequent deck loading:
`GET` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": null,
  "imageUrl": "https://s3.amazonaws.com/tinycards/image/16cb6cbcb086ae0f622d1cfb7553a096",
}
```

### 5. Deck cover update from local file:
`PATCH` https://tinycards.duolingo.com/api/1/decks/{deckID}
```
------<separator>
Content-Disposition: form-data; name="imageFile"; filename="cover.jpg"
Content-Type: image/jpeg
[...bytes...]
------<separator>
Content-Disposition: form-data; name="coverImageUrl"

null
```
Response:
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353"
}
```

### 6. Subsequent deck loading:
`GET` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353"
}
```

### 7. Deck cards update
`PATCH` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353"
}
```
Response:
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353"
}
```

### 8. Subsequent deck loading:
`GET` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353"
}
```

### 9. Deck cover update from Tinycards' image library:
`PATCH` https://tinycards.duolingo.com/api/1/decks/{deckID}
```
------<separator>
Content-Disposition: form-data; name="imageAttribution"

<source URL of the image>
------<separator>
Content-Disposition: form-data; name="imageFile"; filename="cover.jpg"
Content-Type: image/png
[...bytes...]
------<separator>
Content-Disposition: form-data; name="coverImageUrl"

https://d9np3dj86nsu2.cloudfront.net/image/9f6a54aef25a5184620e5762c8430353
```
Response:
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/ada59f16c4e4d8b09f7eee9104ce6bc7",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/ada59f16c4e4d8b09f7eee9104ce6bc7"
}
```

### 10. Subsequent deck loading:
`GET` https://tinycards.duolingo.com/api/1/decks/{deckID}
```json
{
  "coverImageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/ada59f16c4e4d8b09f7eee9104ce6bc7",
  "imageUrl": "https://d9np3dj86nsu2.cloudfront.net/image/ada59f16c4e4d8b09f7eee9104ce6bc7"
}
```

### PR DESCRIPTION
**Pull request by marccarre**
Fixes #54.

**Changelog**:
- add support for covers from URLs (previously: only local files),
- add support for PNG covers (previously: only JPEG),
- segregate responsibilities between `cover` (only used to trigger cover upload), and `imageUrl` & `coverImageUrl` (only used to reflect Tinycards' view of the world).

~**N.B.**: Currently rebased on top of `issues/50-quiz-and-tts-options`, itself rebased on top of `issues/55-more-user-id-cleanup` for tests to pass. Will rebase on top of `master` once #56 and #57 are merged.~

### CODE REVIEW

**Comment by marccarre** [comment]
Now rebased on top of latest `master`.

**Comment by marccarre** [comment]
@floscha, would you be fine releasing a new version of `tinycards-python-api` once this PR is merged? Or is there something else you'd like to have added before that?

**Comment by floscha** [comment]
Hey @marccarre, I'm pretty busy with work these days but I'll have a closer look tonight and then merge the PR and release a new version if everything looks right (which so far it does) 🙂

**Comment by floscha** [comment]
The code looks fine to me. Also, I've tried it out on some of my actual decks and it worked like a charm so I don't see a reason not to merge. Thanks again for the quality work!

**Comment by floscha** [comment]
As promised, I also published a new version to PyPI.

**Comment by marccarre** [comment]
Thank you @floscha! 🎉

**Pull request merged**
