### PR TITLE
Add support for JPEG deck covers

### LINKED ISSUE #47: Feature request: upload of deck's cover
### Description

It is currently **not** possible to create decks with cover images.

Supporting this feature would allow covers to be set programmatically, instead of having to set these manually once the decks are created via `tinycards-python-api`.

### Current state
 
Currently, `Deck`'s `cover` argument is simply ignored:
https://github.com/floscha/tinycards-python-api/blob/cf8f5fc08fb3d5746719eb91c3c6fad8bdadecaa/tinycards/model/deck.py#L9-L29
And even though there is logic to handle `imageFile` in `to_multipart_form`, no value is actually provided:
https://github.com/floscha/tinycards-python-api/blob/0103a53b8393942efcf82b7dd6fb852b00b70686/tinycards/networking/form_utils.py#L15-L22

### PR DESCRIPTION
**Pull request by marccarre**
Fixes #47.

#### Screenshots:

- After deck creation:

Screenshot 2019-03-14 at 06 33 40

- After deck update:

Screenshot 2019-03-16 at 10 55 54

### CODE REVIEW

**Comment by marccarre** [comment]
FYI: currently fixing that unit test I accidentally broke.

**Comment by floscha** [comment]
Hi @marccarre, thanks for the PR. Creating new decks with a cover image works like a charm for me. However, when trying to change the cover of an existing deck and calling `update_deck()`, the change will simply be ignored by the Tinycards backend. While technically this goes beyond #47, which was only about creating decks with a cover, I still believe the option to change covers after the deck's creation could still be helpful for many. What do you think?

**Comment by marccarre** [comment]
Fair point, I'll update this PR accordingly.

**Comment by marccarre** [comment]
FYI:

- when the cover isn't changed, updating the deck sends a `PATCH` with `content-type: application/json`,
- when the cover is changed, updating the deck sends a `PATCH` with `content-type: multipart/form-data`, and an `imageFile` part containing the image's binary data, just like when creating a deck. The payload doesn't change otherwise.

**Comment by marccarre** [comment]
Done:
- updating a deck now also upload its cover,
- testing improved,
- documentation improved.

@floscha, PTAL 🙂

**Comment by floscha** [comment]
The code and tests look good so far. When toying around with the functionality a bit, I found that while adding cover images from local files works as expected, using a URL for images that have been uploaded to the internet already, is simply disregarded by Tinycards. When checking the requests used by the Tinycards web page, you see that it also sends the cover image in binary format, even when selecting an image from a URL.

So I figured one possible solution to this could be trying to download the image from the specified URL and if successful (i.e. getting a 2** HTTP response), submitting the downloaded image as bytes just like when using a local file. One problem to keep in mind with this approach though is to make sure that the image is only downloaded and updated when it was actually changed and not with every update made to the deck. One solution to this could be using the **coverImageUrl** field (which unfortunately is not included in the Python **Deck** class yet). This field appears to be set by the Tinycards backend only after the image was updated (i.e. the local file path has been replaced with the URL to the uploaded version of the image on cloudfront.net). Therefore, it should be possible to simply check if **imageUrl** (i.e. the **cover** property of the **Deck** class) equals **coverImageUrl**.

**Comment by marccarre** [comment]
Sure, sounds good to me!
Would it be fine to do it in a follow-up PR and merge this one @floscha? (It has diverged from `master` quite a bit already, and it would make it easier to parallelise work streams, e.g. #50.)

**Comment by marccarre** [comment]
Issue created. I'll reply there to avoid mixing discussion threads.

**Comment by floscha** [comment]
Thanks a lot! 🙂

Also, I'll bump the version of the library to 0.27 after merging so that your changes are also available when pip-installing the library.

**Comment by marccarre** [comment]
Thanks! 🙂

**Comment by marccarre** [comment]
Looks like #53 and #49 clashed. Opening an issue and will fix soon.

**Pull request merged**
